import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient, type OptionLetter } from '../src/generated/prisma';

const connectionString = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error('DIRECT_URL or DATABASE_URL is not set');
}

const isLocal =
  connectionString.includes('127.0.0.1') ||
  connectionString.includes('localhost');

const adapter = new PrismaPg({
  connectionString,
  ...(isLocal ? {} : { ssl: { rejectUnauthorized: false } }),
});

const prisma = new PrismaClient({ adapter });

type SeedQuestion = {
  text: string;
  reference: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: OptionLetter;
};

const questions: SeedQuestion[] = [
  {
    text: '¿Quién construyó el arca según el relato del Génesis?',
    reference: 'Génesis 6:14',
    optionA: 'Abraham',
    optionB: 'Moisés',
    optionC: 'Noé',
    optionD: 'David',
    correctOption: 'C',
  },
  {
    text: '¿Cuántos días y noches llovió durante el diluvio?',
    reference: 'Génesis 7:12',
    optionA: '7',
    optionB: '40',
    optionC: '12',
    optionD: '70',
    correctOption: 'B',
  },
  {
    text: '¿A quién le prometió Dios que su descendencia sería como las estrellas?',
    reference: 'Génesis 15:5',
    optionA: 'Noé',
    optionB: 'Abraham',
    optionC: 'José',
    optionD: 'Isaac',
    correctOption: 'B',
  },
  {
    text: '¿Quién recibió los Diez Mandamientos en el monte Sinaí?',
    reference: 'Éxodo 20:1-17',
    optionA: 'Aarón',
    optionB: 'Josué',
    optionC: 'Moisés',
    optionD: 'Samuel',
    correctOption: 'C',
  },
  {
    text: '¿Cuál fue el primer mandamiento de los Diez Mandamientos?',
    reference: 'Éxodo 20:3',
    optionA: 'No matarás',
    optionB: 'No tendrás dioses ajenos delante de mí',
    optionC: 'Honra a tu padre y a tu madre',
    optionD: 'No robarás',
    correctOption: 'B',
  },
  {
    text: '¿Quién derribó los muros de Jericó?',
    reference: 'Josué 6:20',
    optionA: 'David',
    optionB: 'Sansón',
    optionC: 'Josué',
    optionD: 'Gedeón',
    correctOption: 'C',
  },
  {
    text: '¿Quién mató a Goliat?',
    reference: '1 Samuel 17:50',
    optionA: 'Saúl',
    optionB: 'Jonatán',
    optionC: 'David',
    optionD: 'Absalón',
    correctOption: 'C',
  },
  {
    text: '¿Quién fue tragado por un gran pez?',
    reference: 'Jonás 1:17',
    optionA: 'Elías',
    optionB: 'Jonás',
    optionC: 'Daniel',
    optionD: 'Job',
    correctOption: 'B',
  },
  {
    text: '¿Cómo sigue la frase: "Jehová es mi pastor..."?',
    reference: 'Salmos 23:1',
    optionA: 'nada me faltará',
    optionB: 'en Él confiaré',
    optionC: 'Él me fortalece',
    optionD: 'su misericordia es eterna',
    correctOption: 'A',
  },
  {
    text: '¿Quién interpretó los sueños del faraón en Egipto?',
    reference: 'Génesis 41:25-32',
    optionA: 'Moisés',
    optionB: 'Daniel',
    optionC: 'José',
    optionD: 'Aarón',
    correctOption: 'C',
  },
  {
    text: '¿Dónde nació Jesús según el Evangelio de Mateo?',
    reference: 'Mateo 2:1',
    optionA: 'Nazaret',
    optionB: 'Jerusalén',
    optionC: 'Belén',
    optionD: 'Capernaúm',
    correctOption: 'C',
  },
  {
    text: '¿Quién bautizó a Jesús?',
    reference: 'Mateo 3:13-16',
    optionA: 'Pedro',
    optionB: 'Juan el Bautista',
    optionC: 'Andrés',
    optionD: 'Santiago',
    correctOption: 'B',
  },
  {
    text: '¿Cuántos discípulos eligió Jesús como apóstoles?',
    reference: 'Lucas 6:13',
    optionA: '7',
    optionB: '10',
    optionC: '12',
    optionD: '70',
    correctOption: 'C',
  },
  {
    text: 'Según Juan, ¿qué dio Dios para que todo aquel que en Él cree no se pierda?',
    reference: 'Juan 3:16',
    optionA: 'La ley',
    optionB: 'A su Hijo unigénito',
    optionC: 'Los profetas',
    optionD: 'El templo',
    correctOption: 'B',
  },
  {
    text: '¿Quién negó a Jesús tres veces?',
    reference: 'Lucas 22:61',
    optionA: 'Judas',
    optionB: 'Tomás',
    optionC: 'Pedro',
    optionD: 'Juan',
    correctOption: 'C',
  },
  {
    text: '¿Quién traicionó a Jesús por treinta monedas de plata?',
    reference: 'Mateo 26:14-15',
    optionA: 'Pedro',
    optionB: 'Judas Iscariote',
    optionC: 'Pilato',
    optionD: 'Herodes',
    correctOption: 'B',
  },
  {
    text: '¿En qué día de la semana resucitó Jesús?',
    reference: 'Marcos 16:9',
    optionA: 'Viernes',
    optionB: 'Sábado',
    optionC: 'El primer día de la semana',
    optionD: 'El tercer día de la semana',
    correctOption: 'C',
  },
  {
    text: '¿Quién escribió la mayoría de las cartas del Nuevo Testamento?',
    reference: 'Romanos 1:1',
    optionA: 'Pedro',
    optionB: 'Juan',
    optionC: 'Pablo',
    optionD: 'Santiago',
    correctOption: 'C',
  },
  {
    text: '¿Cuál es el último libro de la Biblia?',
    reference: 'Apocalipsis 1:1',
    optionA: 'Judas',
    optionB: 'Hebreos',
    optionC: 'Apocalipsis',
    optionD: 'Hechos',
    correctOption: 'C',
  },
  {
    text: '¿Cuál es el fruto del Espíritu mencionado primero en Gálatas?',
    reference: 'Gálatas 5:22',
    optionA: 'Paz',
    optionB: 'Gozo',
    optionC: 'Amor',
    optionD: 'Paciencia',
    correctOption: 'C',
  },
  {
    text: '¿Quién fue el primer hombre según el Génesis?',
    reference: 'Génesis 2:7',
    optionA: 'Adán',
    optionB: 'Caín',
    optionC: 'Set',
    optionD: 'Noé',
    correctOption: 'A',
  },
  {
    text: '¿Cómo se llamaba la primera mujer?',
    reference: 'Génesis 3:20',
    optionA: 'Sara',
    optionB: 'Eva',
    optionC: 'Raquel',
    optionD: 'Rebeca',
    correctOption: 'B',
  },
  {
    text: '¿Quién mató a su hermano Abel?',
    reference: 'Génesis 4:8',
    optionA: 'Set',
    optionB: 'Enoc',
    optionC: 'Caín',
    optionD: 'Lamec',
    correctOption: 'C',
  },
  {
    text: '¿Cuántos hijos de Noé entraron en el arca?',
    reference: 'Génesis 7:13',
    optionA: 'Dos',
    optionB: 'Cuatro',
    optionC: 'Cinco',
    optionD: 'Tres',
    correctOption: 'D',
  },
  {
    text: '¿Qué señal dio Dios a Noé de que no volvería a destruir la tierra con un diluvio?',
    reference: 'Génesis 9:13',
    optionA: 'El arco iris',
    optionB: 'Una estrella',
    optionC: 'Una paloma',
    optionD: 'Una nube blanca',
    correctOption: 'A',
  },
  {
    text: '¿Quién fue la esposa de Abraham?',
    reference: 'Génesis 17:15',
    optionA: 'Raquel',
    optionB: 'Sara',
    optionC: 'Lea',
    optionD: 'Agar',
    correctOption: 'B',
  },
  {
    text: '¿Cómo se llamaba el hijo de la promesa de Abraham y Sara?',
    reference: 'Génesis 21:3',
    optionA: 'Ismael',
    optionB: 'Jacob',
    optionC: 'Isaac',
    optionD: 'Esaú',
    correctOption: 'C',
  },
  {
    text: '¿Quién vendió su primogenitura por un plato de lentejas?',
    reference: 'Génesis 25:34',
    optionA: 'Jacob',
    optionB: 'José',
    optionC: 'Rubén',
    optionD: 'Esaú',
    correctOption: 'D',
  },
  {
    text: '¿Con qué nombre nuevo llamó Dios a Jacob?',
    reference: 'Génesis 32:28',
    optionA: 'Israel',
    optionB: 'Judá',
    optionC: 'Benjamín',
    optionD: 'Efraín',
    correctOption: 'A',
  },
  {
    text: '¿Cuántos hermanos tenía José, hijo de Jacob?',
    reference: 'Génesis 35:22',
    optionA: 'Diez',
    optionB: 'Once',
    optionC: 'Doce',
    optionD: 'Siete',
    correctOption: 'B',
  },
  {
    text: '¿Dónde metieron a José sus hermanos?',
    reference: 'Génesis 37:24',
    optionA: 'Una cueva',
    optionB: 'Una cárcel',
    optionC: 'Una cisterna',
    optionD: 'Una casa',
    correctOption: 'C',
  },
  {
    text: '¿Quién era la madre de Moisés?',
    reference: 'Éxodo 6:20',
    optionA: 'Débora',
    optionB: 'Miriam',
    optionC: 'Ana',
    optionD: 'Jocabed',
    correctOption: 'D',
  },
  {
    text: '¿Qué instrumento musical usó Miriam tras cruzar el mar?',
    reference: 'Éxodo 15:20',
    optionA: 'Un pandero',
    optionB: 'Una arpa',
    optionC: 'Una trompeta',
    optionD: 'Una flauta',
    correctOption: 'A',
  },
  {
    text: '¿Cuántas plagas envió Dios sobre Egipto?',
    reference: 'Éxodo 7–12',
    optionA: 'Siete',
    optionB: 'Diez',
    optionC: 'Doce',
    optionD: 'Tres',
    correctOption: 'B',
  },
  {
    text: '¿Cuál fue la última plaga de Egipto?',
    reference: 'Éxodo 12:29',
    optionA: 'Las ranas',
    optionB: 'Las tinieblas',
    optionC: 'La muerte de los primogénitos',
    optionD: 'El granizo',
    correctOption: 'C',
  },
  {
    text: '¿Qué alimento envió Dios a Israel en el desierto?',
    reference: 'Éxodo 16:15',
    optionA: 'Pan de trigo',
    optionB: 'Uvas',
    optionC: 'Peces',
    optionD: 'Maná',
    correctOption: 'D',
  },
  {
    text: '¿Quién fue el sucesor de Moisés?',
    reference: 'Deuteronomio 31:23',
    optionA: 'Josué',
    optionB: 'Caleb',
    optionC: 'Aarón',
    optionD: 'Eleazar',
    correctOption: 'A',
  },
  {
    text: '¿Cuántos espías envió Moisés a Canaán?',
    reference: 'Números 13:2',
    optionA: 'Diez',
    optionB: 'Doce',
    optionC: 'Siete',
    optionD: 'Dos',
    correctOption: 'B',
  },
  {
    text: '¿Quiénes fueron los dos espías que dieron un buen informe?',
    reference: 'Números 14:6-9',
    optionA: 'Moisés y Aarón',
    optionB: 'David y Jonatán',
    optionC: 'Josué y Caleb',
    optionD: 'Elias y Eliseo',
    correctOption: 'C',
  },
  {
    text: '¿Qué mujer escondió a los espías en Jericó?',
    reference: 'Josué 2:1',
    optionA: 'Débora',
    optionB: 'Rut',
    optionC: 'Ester',
    optionD: 'Rahab',
    correctOption: 'D',
  },
  {
    text: '¿Quién fue la única jueza mencionada en el libro de Jueces?',
    reference: 'Jueces 4:4',
    optionA: 'Débora',
    optionB: 'Jael',
    optionC: 'Ana',
    optionD: 'Abigail',
    correctOption: 'A',
  },
  {
    text: '¿Con qué derrotó Gedeón al ejército madianita?',
    reference: 'Jueces 7:16-20',
    optionA: 'Espadas y escudos',
    optionB: 'Trompetas, cántaros y antorchas',
    optionC: 'Arcos y flechas',
    optionD: 'Caballos',
    correctOption: 'B',
  },
  {
    text: '¿Dónde residía la fuerza de Sansón?',
    reference: 'Jueces 16:17',
    optionA: 'En su cinturón',
    optionB: 'En su anillo',
    optionC: 'En su cabello',
    optionD: 'En su bastón',
    correctOption: 'C',
  },
  {
    text: '¿Quién fue la suegra de Rut?',
    reference: 'Rut 1:2-4',
    optionA: 'Sara',
    optionB: 'Raquel',
    optionC: 'Lea',
    optionD: 'Noemí',
    correctOption: 'D',
  },
  {
    text: '¿Quién redimió a Rut y se casó con ella?',
    reference: 'Rut 4:13',
    optionA: 'Boaz',
    optionB: 'Elimelec',
    optionC: 'Mahlón',
    optionD: 'Quilión',
    correctOption: 'A',
  },
  {
    text: '¿Quién ungió a Saúl como primer rey de Israel?',
    reference: '1 Samuel 10:1',
    optionA: 'Natán',
    optionB: 'Samuel',
    optionC: 'Elí',
    optionD: 'Gad',
    correctOption: 'B',
  },
  {
    text: '¿Quién era el mejor amigo de David?',
    reference: '1 Samuel 18:1',
    optionA: 'Absalón',
    optionB: 'Joab',
    optionC: 'Jonatán',
    optionD: 'Abiatar',
    correctOption: 'C',
  },
  {
    text: '¿De qué ciudad era David?',
    reference: '1 Samuel 17:12',
    optionA: 'Jerusalén',
    optionB: 'Hebón',
    optionC: 'Siquem',
    optionD: 'Belén',
    correctOption: 'D',
  },
  {
    text: '¿Quién fue el hijo de David que se rebeló contra él?',
    reference: '2 Samuel 15:10',
    optionA: 'Absalón',
    optionB: 'Salomón',
    optionC: 'Adonías',
    optionD: 'Amnón',
    correctOption: 'A',
  },
  {
    text: '¿Quién construyó el primer templo en Jerusalén?',
    reference: '1 Reyes 6:1',
    optionA: 'David',
    optionB: 'Salomón',
    optionC: 'Roboam',
    optionD: 'Ezequías',
    correctOption: 'B',
  },
  {
    text: '¿Qué reina visitó a Salomón para probar su sabiduría?',
    reference: '1 Reyes 10:1',
    optionA: 'La reina Ester',
    optionB: 'Jezabel',
    optionC: 'La reina de Sabá',
    optionD: 'Atalía',
    correctOption: 'C',
  },
  {
    text: '¿Quién desafió a los profetas de Baal en el monte Carmelo?',
    reference: '1 Reyes 18:21-39',
    optionA: 'Eliseo',
    optionB: 'Isaías',
    optionC: 'Jeremías',
    optionD: 'Elías',
    correctOption: 'D',
  },
  {
    text: '¿Cómo fue llevado Elías al cielo?',
    reference: '2 Reyes 2:11',
    optionA: 'En un carro de fuego',
    optionB: 'En una nube',
    optionC: 'En un torbellino de agua',
    optionD: 'En un sueño',
    correctOption: 'A',
  },
  {
    text: '¿Quién recibió el manto de Elías?',
    reference: '2 Reyes 2:13',
    optionA: 'Isaías',
    optionB: 'Eliseo',
    optionC: 'Jonás',
    optionD: 'Amós',
    correctOption: 'B',
  },
  {
    text: '¿Qué mujer judía se convirtió en reina de Persia?',
    reference: 'Ester 2:17',
    optionA: 'Débora',
    optionB: 'Rut',
    optionC: 'Ester',
    optionD: 'Abigail',
    correctOption: 'C',
  },
  {
    text: '¿Quién planeó destruir a los judíos en el libro de Ester?',
    reference: 'Ester 3:6',
    optionA: 'Asuero',
    optionB: 'Mardoqueo',
    optionC: 'Nabucodonosor',
    optionD: 'Amán',
    correctOption: 'D',
  },
  {
    text: '¿Quién dijo: "Aunque él me mate, en él esperaré"?',
    reference: 'Job 13:15',
    optionA: 'Job',
    optionB: 'David',
    optionC: 'Salomón',
    optionD: 'Isaías',
    correctOption: 'A',
  },
  {
    text: '¿Quién escribió la mayoría de los Proverbios?',
    reference: 'Proverbios 1:1',
    optionA: 'David',
    optionB: 'Salomón',
    optionC: 'Moisés',
    optionD: 'Job',
    correctOption: 'B',
  },
  {
    text: 'En el Salmo 27, ¿cómo describe David al Señor?',
    reference: 'Salmos 27:1',
    optionA: 'Mi escudo y mi torre',
    optionB: 'Mi roca y mi fortaleza',
    optionC: 'Mi luz y mi salvación',
    optionD: 'Mi pastor y mi guía',
    correctOption: 'C',
  },
  {
    text: '¿Quién escribió: "Vanidad de vanidades, todo es vanidad"?',
    reference: 'Eclesiastés 1:2',
    optionA: 'David',
    optionB: 'Isaías',
    optionC: 'Jeremías',
    optionD: 'El Predicador (Salomón)',
    correctOption: 'D',
  },
  {
    text: '¿Qué profeta vio al Señor en el templo y dijo: "Heme aquí, envíame a mí"?',
    reference: 'Isaías 6:8',
    optionA: 'Isaías',
    optionB: 'Ezequiel',
    optionC: 'Jeremías',
    optionD: 'Daniel',
    correctOption: 'A',
  },
  {
    text: '¿Quién es conocido como el "profeta llorón"?',
    reference: 'Jeremías 9:1',
    optionA: 'Isaías',
    optionB: 'Jeremías',
    optionC: 'Oseas',
    optionD: 'Amós',
    correctOption: 'B',
  },
  {
    text: '¿En qué foso fue echado Daniel?',
    reference: 'Daniel 6:16',
    optionA: 'De serpientes',
    optionB: 'De fuego',
    optionC: 'De leones',
    optionD: 'De agua',
    correctOption: 'C',
  },
  {
    text: '¿Cuántos jóvenes hebreos fueron echados al horno de fuego?',
    reference: 'Daniel 3:20',
    optionA: 'Dos',
    optionB: 'Cuatro',
    optionC: 'Cinco',
    optionD: 'Tres',
    correctOption: 'D',
  },
  {
    text: '¿Cómo se llamaban los tres amigos de Daniel?',
    reference: 'Daniel 1:7',
    optionA: 'Sadrac, Mesac y Abed-nego',
    optionB: 'Pedro, Juan y Santiago',
    optionC: 'Elías, Eliseo y Amós',
    optionD: 'Job, Elifaz y Bildad',
    correctOption: 'A',
  },
  {
    text: '¿A qué ciudad fue enviada Jonás a predicar?',
    reference: 'Jonás 1:2',
    optionA: 'Babilonia',
    optionB: 'Nínive',
    optionC: 'Tiro',
    optionD: 'Sidón',
    correctOption: 'B',
  },
  {
    text: '¿Quién interpretó la escritura en la pared ante Belsasar?',
    reference: 'Daniel 5:17',
    optionA: 'José',
    optionB: 'Nehemías',
    optionC: 'Daniel',
    optionD: 'Esdras',
    correctOption: 'C',
  },
  {
    text: '¿Quién reconstruyó los muros de Jerusalén tras el exilio?',
    reference: 'Nehemías 2:17-18',
    optionA: 'Esdras',
    optionB: 'Zorobabel',
    optionC: 'Daniel',
    optionD: 'Nehemías',
    correctOption: 'D',
  },
  {
    text: '¿Quién anunció el nacimiento de Jesús a María?',
    reference: 'Lucas 1:26-31',
    optionA: 'El ángel Gabriel',
    optionB: 'El ángel Miguel',
    optionC: 'Un pastor',
    optionD: 'Juan el Bautista',
    correctOption: 'A',
  },
  {
    text: '¿Quién era el esposo de María?',
    reference: 'Mateo 1:18',
    optionA: 'Pedro',
    optionB: 'José',
    optionC: 'Zacarías',
    optionD: 'Simón',
    correctOption: 'B',
  },
  {
    text: '¿Quiénes visitaron a Jesús recién nacido según Mateo?',
    reference: 'Mateo 2:1-11',
    optionA: 'Los pastores',
    optionB: 'Los fariseos',
    optionC: 'Los magos',
    optionD: 'Los saduceos',
    correctOption: 'C',
  },
  {
    text: '¿Cuántos días ayunó Jesús en el desierto?',
    reference: 'Mateo 4:2',
    optionA: 'Siete',
    optionB: 'Doce',
    optionC: 'Treinta',
    optionD: 'Cuarenta',
    correctOption: 'D',
  },
  {
    text: '¿Quiénes fueron los primeros discípulos llamados por Jesús?',
    reference: 'Mateo 4:18-20',
    optionA: 'Pedro y Andrés',
    optionB: 'Juan y Santiago',
    optionC: 'Felipe y Natanael',
    optionD: 'Mateo y Tomás',
    correctOption: 'A',
  },
  {
    text: '¿Qué profesión tenía Mateo antes de seguir a Jesús?',
    reference: 'Mateo 9:9',
    optionA: 'Pescador',
    optionB: 'Publicano (cobrador de impuestos)',
    optionC: 'Carpintero',
    optionD: 'Sacerdote',
    correctOption: 'B',
  },
  {
    text: '¿En qué monte pronunció Jesús las Bienaventuranzas?',
    reference: 'Mateo 5:1-12',
    optionA: 'Monte Sinaí',
    optionB: 'Monte Carmelo',
    optionC: 'El monte (Sermón del Monte)',
    optionD: 'Monte de los Olivos',
    correctOption: 'C',
  },
  {
    text: '¿Cuál es la primera Bienaventuranza?',
    reference: 'Mateo 5:3',
    optionA: 'Bienaventurados los mansos',
    optionB: 'Bienaventurados los que lloran',
    optionC: 'Bienaventurados los pacificadores',
    optionD: 'Bienaventurados los pobres en espíritu',
    correctOption: 'D',
  },
  {
    text: '¿Cuántos panes usó Jesús para alimentar a unos cinco mil?',
    reference: 'Juan 6:9',
    optionA: 'Cinco panes de cebada',
    optionB: 'Siete panes',
    optionC: 'Doce panes',
    optionD: 'Dos panes',
    correctOption: 'A',
  },
  {
    text: '¿Qué pescados acompañaron los panes en la multiplicación?',
    reference: 'Juan 6:9',
    optionA: 'Tres',
    optionB: 'Dos',
    optionC: 'Cinco',
    optionD: 'Siete',
    correctOption: 'B',
  },
  {
    text: '¿Sobre qué caminó Jesús en el mar de Galilea?',
    reference: 'Mateo 14:25',
    optionA: 'Sobre las nubes',
    optionB: 'Sobre la arena',
    optionC: 'Sobre el agua',
    optionD: 'Sobre las piedras',
    correctOption: 'C',
  },
  {
    text: '¿Quién también caminó sobre el agua por un momento?',
    reference: 'Mateo 14:29',
    optionA: 'Juan',
    optionB: 'Andrés',
    optionC: 'Tomás',
    optionD: 'Pedro',
    correctOption: 'D',
  },
  {
    text: '¿A quién resucitó Jesús después de cuatro días en el sepulcro?',
    reference: 'Juan 11:43-44',
    optionA: 'Lázaro',
    optionB: 'Jairo',
    optionC: 'El hijo de la viuda',
    optionD: 'Tabita',
    correctOption: 'A',
  },
  {
    text: '¿Cómo se llamaban las hermanas de Lázaro?',
    reference: 'Juan 11:1',
    optionA: 'Sara y Rebeca',
    optionB: 'María y Marta',
    optionC: 'Ana y Elisabet',
    optionD: 'Rut y Noemí',
    correctOption: 'B',
  },
  {
    text: '¿Quién subió a un sicómoro para ver a Jesús?',
    reference: 'Lucas 19:2-4',
    optionA: 'Nicodemo',
    optionB: 'Bartimeo',
    optionC: 'Zaqueo',
    optionD: 'Simón',
    correctOption: 'C',
  },
  {
    text: '¿Qué oficio tenía Zaqueo?',
    reference: 'Lucas 19:2',
    optionA: 'Pescador',
    optionB: 'Fariseo',
    optionC: 'Sacerdote',
    optionD: 'Jefe de publicanos',
    correctOption: 'D',
  },
  {
    text: '¿Quién ungió los pies de Jesús con perfume costoso?',
    reference: 'Juan 12:3',
    optionA: 'María',
    optionB: 'Marta',
    optionC: 'Salomé',
    optionD: 'Juana',
    correctOption: 'A',
  },
  {
    text: '¿En qué jardín oró Jesús antes de ser arrestado?',
    reference: 'Mateo 26:36',
    optionA: 'Edén',
    optionB: 'Getsemaní',
    optionC: 'Jericó',
    optionD: 'Betania',
    correctOption: 'B',
  },
  {
    text: '¿Quién lavó sus manos declarando inocente a Jesús?',
    reference: 'Mateo 27:24',
    optionA: 'Herodes',
    optionB: 'Caifás',
    optionC: 'Poncio Pilato',
    optionD: 'Anás',
    correctOption: 'C',
  },
  {
    text: '¿Quién ayudó a cargar la cruz de Jesús?',
    reference: 'Mateo 27:32',
    optionA: 'José de Arimatea',
    optionB: 'Nicodemo',
    optionC: 'Simón Pedro',
    optionD: 'Simón de Cirene',
    correctOption: 'D',
  },
  {
    text: '¿En qué lugar fue crucificado Jesús?',
    reference: 'Juan 19:17',
    optionA: 'El Gólgota',
    optionB: 'El Monte de los Olivos',
    optionC: 'Getsemaní',
    optionD: 'Betania',
    correctOption: 'A',
  },
  {
    text: '¿Quién pidió el cuerpo de Jesús para sepultarlo?',
    reference: 'Mateo 27:57-60',
    optionA: 'Pedro',
    optionB: 'José de Arimatea',
    optionC: 'Juan',
    optionD: 'Nicodemo',
    correctOption: 'B',
  },
  {
    text: '¿Quién fue la primera persona en ver a Jesús resucitado según Juan?',
    reference: 'Juan 20:14-16',
    optionA: 'Pedro',
    optionB: 'Juan',
    optionC: 'María Magdalena',
    optionD: 'Tomás',
    correctOption: 'C',
  },
  {
    text: '¿Quién dudó de la resurrección hasta ver las heridas de Jesús?',
    reference: 'Juan 20:24-28',
    optionA: 'Pedro',
    optionB: 'Juan',
    optionC: 'Andrés',
    optionD: 'Tomás',
    correctOption: 'D',
  },
  {
    text: '¿En qué ciudad descendió el Espíritu Santo en Pentecostés?',
    reference: 'Hechos 2:1-4',
    optionA: 'Jerusalén',
    optionB: 'Antioquía',
    optionC: 'Roma',
    optionD: 'Corinto',
    correctOption: 'A',
  },
  {
    text: '¿Quién predicó el sermón de Pentecostés?',
    reference: 'Hechos 2:14',
    optionA: 'Juan',
    optionB: 'Pedro',
    optionC: 'Santiago',
    optionD: 'Esteban',
    correctOption: 'B',
  },
  {
    text: '¿Quién fue el primer mártir cristiano?',
    reference: 'Hechos 7:59-60',
    optionA: 'Santiago',
    optionB: 'Pedro',
    optionC: 'Esteban',
    optionD: 'Pablo',
    correctOption: 'C',
  },
  {
    text: '¿En el camino a qué ciudad se convirtió Saulo?',
    reference: 'Hechos 9:3',
    optionA: 'Jerusalén',
    optionB: 'Roma',
    optionC: 'Antioquía',
    optionD: 'Damasco',
    correctOption: 'D',
  },
  {
    text: '¿Cómo se llamaba Saulo después de su conversión?',
    reference: 'Hechos 13:9',
    optionA: 'Pablo',
    optionB: 'Pedro',
    optionC: 'Silas',
    optionD: 'Bernabé',
    correctOption: 'A',
  },
  {
    text: '¿Quién acompañó a Pablo en su primer viaje misionero?',
    reference: 'Hechos 13:2',
    optionA: 'Timoteo',
    optionB: 'Bernabé',
    optionC: 'Tito',
    optionD: 'Lucas',
    correctOption: 'B',
  },
  {
    text: '¿Quién era el joven discípulo a quien Pablo escribió dos cartas?',
    reference: '1 Timoteo 1:2',
    optionA: 'Tito',
    optionB: 'Filemón',
    optionC: 'Timoteo',
    optionD: 'Onésimo',
    correctOption: 'C',
  },
  {
    text: '¿Quién escribió el libro de los Hechos?',
    reference: 'Hechos 1:1',
    optionA: 'Pedro',
    optionB: 'Pablo',
    optionC: 'Juan',
    optionD: 'Lucas',
    correctOption: 'D',
  },
  {
    text: 'Según Romanos, ¿para quiénes todas las cosas ayudan a bien?',
    reference: 'Romanos 8:28',
    optionA: 'Los que aman a Dios',
    optionB: 'Los fariseos',
    optionC: 'Solo los apóstoles',
    optionD: 'Los ricos',
    correctOption: 'A',
  },
  {
    text: '¿Quién dijo: "Todo lo puedo en Cristo que me fortalece"?',
    reference: 'Filipenses 4:13',
    optionA: 'Pedro',
    optionB: 'Pablo',
    optionC: 'Juan',
    optionD: 'Santiago',
    correctOption: 'B',
  },
  {
    text: 'Según Efesios, ¿por qué medio somos salvos?',
    reference: 'Efesios 2:8',
    optionA: 'Por las obras de la ley',
    optionB: 'Por ofrendas',
    optionC: 'Por gracia, mediante la fe',
    optionD: 'Por el bautismo solo',
    correctOption: 'C',
  },
  {
    text: '¿Cómo define Hebreos la fe?',
    reference: 'Hebreos 11:1',
    optionA: 'Una emoción',
    optionB: 'Una religión',
    optionC: 'Una tradición',
    optionD: 'La certeza de lo que se espera',
    correctOption: 'D',
  },
  {
    text: '¿Quién escribió el Apocalipsis?',
    reference: 'Apocalipsis 1:1',
    optionA: 'Juan',
    optionB: 'Pedro',
    optionC: 'Pablo',
    optionD: 'Santiago',
    correctOption: 'A',
  },
  {
    text: '¿En qué isla estaba Juan cuando recibió la revelación?',
    reference: 'Apocalipsis 1:9',
    optionA: 'Creta',
    optionB: 'Patmos',
    optionC: 'Chipre',
    optionD: 'Malta',
    correctOption: 'B',
  },
  {
    text: '¿A cuántas iglesias escribe Juan en Apocalipsis?',
    reference: 'Apocalipsis 1:11',
    optionA: 'Cinco',
    optionB: 'Doce',
    optionC: 'Siete',
    optionD: 'Diez',
    correctOption: 'C',
  },
  {
    text: '¿Cuál es el primer libro de la Biblia?',
    reference: 'Génesis 1:1',
    optionA: 'Éxodo',
    optionB: 'Salmos',
    optionC: 'Mateo',
    optionD: 'Génesis',
    correctOption: 'D',
  },
  {
    text: '¿Cuántos libros tiene aproximadamente el Antiguo Testamento protestante?',
    reference: 'Canon protestante',
    optionA: '39',
    optionB: '27',
    optionC: '66',
    optionD: '12',
    correctOption: 'A',
  },
  {
    text: '¿Cuántos libros tiene el Nuevo Testamento?',
    reference: 'Canon del NT',
    optionA: '39',
    optionB: '27',
    optionC: '66',
    optionD: '12',
    correctOption: 'B',
  },
  {
    text: '¿Quién dijo: "Yo soy el camino, la verdad y la vida"?',
    reference: 'Juan 14:6',
    optionA: 'Pedro',
    optionB: 'Pablo',
    optionC: 'Jesús',
    optionD: 'Juan',
    correctOption: 'C',
  },
  {
    text: '¿Quién dijo: "Así alumbre vuestra luz delante de los hombres"?',
    reference: 'Mateo 5:16',
    optionA: 'Moisés',
    optionB: 'Isaías',
    optionC: 'Pablo',
    optionD: 'Jesús',
    correctOption: 'D',
  },
  {
    text: '¿Cuál es el mandamiento más grande según Jesús?',
    reference: 'Mateo 22:37-38',
    optionA: 'Amarás al Señor tu Dios',
    optionB: 'No matarás',
    optionC: 'Honra a tu padre y a tu madre',
    optionD: 'No mentirás',
    correctOption: 'A',
  },
  {
    text: '¿Cuál es el segundo mandamiento grande según Jesús?',
    reference: 'Mateo 22:39',
    optionA: 'No robarás',
    optionB: 'Amarás a tu prójimo como a ti mismo',
    optionC: 'Guardarás el sábado',
    optionD: 'No codiciarás',
    correctOption: 'B',
  },
  {
    text: '¿Quién lavó los pies de sus discípulos?',
    reference: 'Juan 13:5',
    optionA: 'Pedro',
    optionB: 'Juan',
    optionC: 'Jesús',
    optionD: 'María',
    correctOption: 'C',
  },
  {
    text: '¿En qué ciudad nacieron Pablo según Hechos?',
    reference: 'Hechos 22:3',
    optionA: 'Jerusalén',
    optionB: 'Roma',
    optionC: 'Antioquía',
    optionD: 'Tarso',
    correctOption: 'D',
  },
  {
    text: '¿Quién era la madre de Juan el Bautista?',
    reference: 'Lucas 1:13',
    optionA: 'Elisabet',
    optionB: 'María',
    optionC: 'Ana',
    optionD: 'Salomé',
    correctOption: 'A',
  },
  {
    text: '¿Qué ofrenda presentó Caín a Dios?',
    reference: 'Génesis 4:3',
    optionA: 'Un cordero',
    optionB: 'Del fruto de la tierra',
    optionC: 'Incienso',
    optionD: 'Oro',
    correctOption: 'B',
  },
  {
    text: '¿Cuántos días estuvo Jonás en el vientre del pez?',
    reference: 'Jonás 1:17',
    optionA: 'Uno',
    optionB: 'Siete',
    optionC: 'Tres',
    optionD: 'Cuarenta',
    correctOption: 'C',
  },
  {
    text: '¿Quién fue llevado al cielo sin morir, junto con Elías?',
    reference: 'Génesis 5:24',
    optionA: 'Moisés',
    optionB: 'Abraham',
    optionC: 'Noé',
    optionD: 'Enoc',
    correctOption: 'D',
  },
];

/** Textos viejos que spoileaban; se actualizan en DB antes del createMany. */
const questionRewrites: { oldText: string; question: SeedQuestion }[] = [
  {
    oldText: '¿En qué libro aparece el Salmo 23: "Jehová es mi pastor"?',
    question: {
      text: '¿Cómo sigue la frase: "Jehová es mi pastor..."?',
      reference: 'Salmos 23:1',
      optionA: 'nada me faltará',
      optionB: 'en Él confiaré',
      optionC: 'Él me fortalece',
      optionD: 'su misericordia es eterna',
      correctOption: 'A',
    },
  },
  {
    oldText: '¿Cuál es el versículo: "Porque de tal manera amó Dios al mundo..."?',
    question: {
      text: 'Según Juan, ¿qué dio Dios para que todo aquel que en Él cree no se pierda?',
      reference: 'Juan 3:16',
      optionA: 'La ley',
      optionB: 'A su Hijo unigénito',
      optionC: 'Los profetas',
      optionD: 'El templo',
      correctOption: 'B',
    },
  },
  {
    oldText: '¿En qué animal metieron a José sus hermanos?',
    question: {
      text: '¿Dónde metieron a José sus hermanos?',
      reference: 'Génesis 37:24',
      optionA: 'Una cueva',
      optionB: 'Una cárcel',
      optionC: 'Una cisterna',
      optionD: 'Una casa',
      correctOption: 'C',
    },
  },
  {
    oldText: '¿Cuál es el versículo: "El Señor es mi luz y mi salvación"?',
    question: {
      text: 'En el Salmo 27, ¿cómo describe David al Señor?',
      reference: 'Salmos 27:1',
      optionA: 'Mi escudo y mi torre',
      optionB: 'Mi roca y mi fortaleza',
      optionC: 'Mi luz y mi salvación',
      optionD: 'Mi pastor y mi guía',
      correctOption: 'C',
    },
  },
  {
    oldText: '¿Cuál es el versículo: "Todas las cosas cooperan para bien"?',
    question: {
      text: 'Según Romanos, ¿para quiénes todas las cosas ayudan a bien?',
      reference: 'Romanos 8:28',
      optionA: 'Los que aman a Dios',
      optionB: 'Los fariseos',
      optionC: 'Solo los apóstoles',
      optionD: 'Los ricos',
      correctOption: 'A',
    },
  },
  {
    oldText: '¿Cuál es el versículo: "Todo lo puedo en Cristo que me fortalece"?',
    question: {
      text: '¿Quién dijo: "Todo lo puedo en Cristo que me fortalece"?',
      reference: 'Filipenses 4:13',
      optionA: 'Pedro',
      optionB: 'Pablo',
      optionC: 'Juan',
      optionD: 'Santiago',
      correctOption: 'B',
    },
  },
  {
    oldText: '¿Cuál es el versículo: "Por gracia sois salvos por medio de la fe"?',
    question: {
      text: 'Según Efesios, ¿por qué medio somos salvos?',
      reference: 'Efesios 2:8',
      optionA: 'Por las obras de la ley',
      optionB: 'Por ofrendas',
      optionC: 'Por gracia, mediante la fe',
      optionD: 'Por el bautismo solo',
      correctOption: 'C',
    },
  },
];

async function main() {
  let rewritten = 0;
  for (const { oldText, question } of questionRewrites) {
    const result = await prisma.question.updateMany({
      where: { text: oldText },
      data: question,
    });
    rewritten += result.count;
  }

  const result = await prisma.question.createMany({
    data: questions,
    skipDuplicates: true,
  });

  const total = await prisma.question.count();
  console.log(
    `Seed OK: rewritten ${rewritten}, inserted ${result.count}, total questions: ${total}`,
  );
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
